name: Branch build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  OCTOPUS_CLI_SERVER: ${{ secrets.OCTOPUS_URL }}
  OCTOPUS_CLI_API_KEY: ${{ secrets.OCTOPUS_CLI_API_KEY }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}
      OCTOPUS_CLI_API_KEY: ${{ secrets.INTEGRATIONS_API_KEY }}

  create-release:
    name: "Create Release"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install Octopus CLI 🐙
        uses: OctopusDeploy/install-octopus-cli-action@v1.1.7

      - name: Create a release in Octopus Deploy 🐙
        uses: OctopusDeploy/create-release-action@v1.1.1
        with:
          space: "Integrations"
          project: "Azure DevOps Extension"
          package_version: ${{ needs.build.outputs.PACKAGE_VERSION }}
          git_ref: ${{ (github.ref_type == 'tag' && 'main' ) || (github.head_ref || github.ref) }}
          git_commit: ${{ github.event.after || github.event.pull_request.head.sha }}
