name: Build

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OCTOPUS_ENVIRONMENT: Production
      OCTOPUS_VERSION: 4.3.${{ github.run_number }}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Build
        run: |
          npm install
          npm run build -- --extensionVersion $OCTOPUS_VERSION

      - name: Replace versions in tasks and create vsix
        run: |
          pwsh ./pack.ps1 -environment $OCTOPUS_ENVIRONMENT -version $OCTOPUS_VERSION

      - name: Create Package
        run: |
          tar -czf OctoTFS.vsix.$OCTOPUS_VERSION.tar.gz ./dist/Artifacts/$OCTOPUS_ENVIRONMENT/*.vsix

      - name: Push Package
        uses: burtonr/octopus-cli-action@7.4.4
        env:
          OCTOPUS_CLI_SERVER: ${{ secrets.OCTOPUS_URL }}
          OCTOPUS_CLI_API_KEY: ${{ secrets.INTEGRATIONS_API_KEY }}
        with:
          command: push --space "Integrations" --package OctoTFS.vsix.$OCTOPUS_VERSION.tar.gz --overwrite-mode OverwriteExisting
      - name: Create Release
        uses: burtonr/octopus-cli-action@7.4.4
        env:
          OCTOPUS_CLI_SERVER: ${{ secrets.OCTOPUS_URL }}
          OCTOPUS_CLI_API_KEY: ${{ secrets.INTEGRATIONS_API_KEY }}
        with:
          command: create-release --space "Integrations" --project "Azure DevOps Extension" --package $OCTOPUS_VERSION

